#!/usr/bin/env bash
# Idempotent VPS bootstrap for Artillery ERP (Ubuntu/Debian).
# Requires env vars — never embed passwords in this script.
#
# Required:
#   ARTILLERY_DB_PASSWORD       — password for artillery_app role
#   ARTILLERY_READONLY_PASSWORD — password for artillery_readonly role
# Optional:
#   ARTILLERY_DOMAIN            — e.g. api.example.com (Nginx server_name)
#   ARTILLERY_API_PORT          — default 4000
#   ARTILLERY_SSH_PORT            — default 22 (UFW allow rule)
#
# Usage:
#   export ARTILLERY_DB_PASSWORD='...'
#   export ARTILLERY_READONLY_PASSWORD='...'
#   export ARTILLERY_DOMAIN='api.example.com'
#   sudo -E bash scripts/migration/setup-vps.sh

set -euo pipefail

ARTILLERY_API_PORT="${ARTILLERY_API_PORT:-4000}"
ARTILLERY_SSH_PORT="${ARTILLERY_SSH_PORT:-22}"
ARTILLERY_DOMAIN="${ARTILLERY_DOMAIN:-api.example.com}"

if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
  echo "Run as root: sudo -E bash $0" >&2
  exit 1
fi

if [[ -z "${ARTILLERY_DB_PASSWORD:-}" || -z "${ARTILLERY_READONLY_PASSWORD:-}" ]]; then
  echo "Set ARTILLERY_DB_PASSWORD and ARTILLERY_READONLY_PASSWORD before running." >&2
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive

echo "==> Updating packages"
apt-get update -qq
apt-get install -y -qq curl gnupg lsb-release ca-certificates ufw nginx

echo "==> Configuring UFW"
ufw --force reset || true
ufw default deny incoming
ufw default allow outgoing
ufw allow "${ARTILLERY_SSH_PORT}/tcp" comment 'SSH'
ufw allow 80/tcp comment 'HTTP'
ufw allow 443/tcp comment 'HTTPS'
ufw --force enable
echo "NOTE: Install and enable fail2ban manually for SSH brute-force protection:"
echo "  apt-get install -y fail2ban && systemctl enable --now fail2ban"

echo "==> Installing PostgreSQL 16"
if ! command -v psql >/dev/null 2>&1 || ! psql --version | grep -q '16'; then
  install -d /usr/share/postgresql-common/pgdg
  curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc \
    | gpg --dearmor -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.gpg
  echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.gpg] \
https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" \
    > /etc/apt/sources.list.d/pgdg.list
  apt-get update -qq
  apt-get install -y -qq postgresql-16 postgresql-client-16
fi
systemctl enable postgresql
systemctl start postgresql

echo "==> Creating databases and roles"
sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'artillery_app') THEN
    CREATE ROLE artillery_app LOGIN PASSWORD '${ARTILLERY_DB_PASSWORD}';
  ELSE
    ALTER ROLE artillery_app WITH PASSWORD '${ARTILLERY_DB_PASSWORD}';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'artillery_readonly') THEN
    CREATE ROLE artillery_readonly LOGIN PASSWORD '${ARTILLERY_READONLY_PASSWORD}';
  ELSE
    ALTER ROLE artillery_readonly WITH PASSWORD '${ARTILLERY_READONLY_PASSWORD}';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE artillery_erp OWNER artillery_app'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'artillery_erp')\gexec

SELECT 'CREATE DATABASE artillery_erp_staging OWNER artillery_app'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'artillery_erp_staging')\gexec

GRANT CONNECT ON DATABASE artillery_erp TO artillery_readonly;
GRANT CONNECT ON DATABASE artillery_erp_staging TO artillery_readonly;
SQL

for db in artillery_erp artillery_erp_staging; do
  sudo -u postgres psql -d "$db" -v ON_ERROR_STOP=1 <<SQL
GRANT USAGE ON SCHEMA public TO artillery_app, artillery_readonly;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO artillery_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO artillery_app;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO artillery_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO artillery_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO artillery_readonly;
SQL
done

echo "==> Installing Node.js 20"
if ! command -v node >/dev/null 2>&1 || ! node -v | grep -q '^v20'; then
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y -qq nodejs
fi

echo "==> Installing PM2"
if ! command -v pm2 >/dev/null 2>&1; then
  npm install -g pm2
fi

echo "==> Writing Nginx reverse proxy template"
NGINX_SITE="/etc/nginx/sites-available/artillery-api"
cat > "$NGINX_SITE" <<NGINX
# Artillery ERP API — generated by setup-vps.sh
# Point DNS A record for ${ARTILLERY_DOMAIN} to this server, then:
#   certbot --nginx -d ${ARTILLERY_DOMAIN}

upstream artillery_api {
    server 127.0.0.1:${ARTILLERY_API_PORT};
    keepalive 32;
}

server {
    listen 80;
    server_name ${ARTILLERY_DOMAIN};

    client_max_body_size 25m;

    location / {
        proxy_pass http://artillery_api;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Connection "";
    }
}
NGINX

ln -sf "$NGINX_SITE" /etc/nginx/sites-enabled/artillery-api
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl reload nginx

echo ""
echo "==> VPS bootstrap complete"
echo "  PostgreSQL databases: artillery_erp, artillery_erp_staging"
echo "  Roles: artillery_app, artillery_readonly"
echo "  API upstream: localhost:${ARTILLERY_API_PORT}"
echo "  Nginx site: ${ARTILLERY_DOMAIN}"
echo ""
echo "Next steps:"
echo "  1. Import schema/data: scripts/migration/import-to-vps.sh"
echo "  2. Deploy backend/ and start with PM2"
echo "  3. Enable TLS: certbot --nginx -d ${ARTILLERY_DOMAIN}"
